module.exports = {
  // 单行最大长度
  printWidth: 80,
  // 缩进的字符数
  tabWidth: 2,
  // 使用tab缩进
  useTabs: false,
  // 语句末尾必须加分号
  semi: true,
  // 字符串使用单引号
  singleQuote: true,
  // 在对象的键上使用单引号
  quoteProps: 'as-needed',
  // 在jsx中使用单引号
  jsxSingleQuote: false,
  // 添加尾部逗号
  trailingComma: 'all',
  // 在对象大括号两侧添加空格
  bracketSpacing: true,
  jsxBracketSameLine: false,
  // 箭头函数参数加括号
  arrowParens: 'always',
  rangeStart: 0,
  rangeEnd: Infinity,
  proseWrap: 'preserve',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  embeddedLanguageFormatting: 'auto',
};
